### PR TITLE
Clarify Drupal settings in non-drupal build flavor

### PR DESCRIPTION
**Pull request by mrkschan**

### CODE REVIEW

**Comment by Crell** [comment]
Mm, this is wrong.  Especially with the new D8 template that doesn't use the Drupal build flavor anymore.  Checking settings.local.php into the repository is against Drupal recommended practices.

**Comment by mrkschan** [comment]
So, do we need a section for Drupal 8 and another one for Drupal 7? This is an issue we always see on Zendesk.

**Comment by pjcdawkins** [comment]
The `settings.php` page is a bit of a mess - I suggest #288 instead

**Comment by Crell** [comment]
Closing in favor of #288

**Pull request closed without merging**
