### PR TITLE
Update solr.md to reflect removal of the search_api_solr_defaults module

### PR DESCRIPTION
**Pull request by alexharriesredactive**
For the D.o ticket, @see https://www.drupal.org/project/search_api_solr/issues/3283191#comment-14560693 For default config, @see https://git.drupalcode.org/project/search_api_solr/-/commit/1568d2b#4f547dbec1b001e0aa88f925637aa20132616c30

## Why

Closes #{ISSUE_NUMBER}

### CODE REVIEW

**Comment by CollierCZ** [comment]
Thanks for the fix, @alexharriesredactive ! Definitely appreciated. Could you help me understand why the defaults you added are different than the ones you linked? I'd prefer to just link to the code elsewhere so I don't have to follow updates to see if it's outdated. But if it needs a different format or options, that's different.

**Comment by alexharriesredactive** [comment]
Hi @CollierCZ,

> Could you help me understand why the defaults you added are different than the ones you linked?

Sorry, could you let me know which defaults you mean, please?

I copied the deleted yaml config from here: https://git.drupalcode.org/project/search_api_solr/-/commit/1568d2b#4f547dbec1b001e0aa88f925637aa20132616c30

... into here: https://github.com/platformsh/platformsh-docs/pull/2678/commits/92cbd24b3d4603adb4987ace5f64dfc0c33cbf17

... unless I mis-read something?

Best wishes :)

Alex

**Comment by CollierCZ** [comment]
I see this file in the linked MR:

```yaml
langcode: en
name: 'Solr Server'
description: 'Default Solr server created by the Solr Search Defaults module'
status: true
id: default_solr_server
backend: search_api_solr
backend_config:
  connector: standard
  connector_config:
    scheme: http
    host: localhost
    port: 8983
    path: /
    core: drupal
    timeout: 5
    index_timeout: 10
    optimize_timeout: 15
    finalize_timeout: 30
    commit_within: 10
    solr_version: ''
    http_method: AUTO
    jmx: false
    jts: false
    solr_install_dir: ''
    skip_schema_check: false
  retrieve_data: false
  highlight_data: false
  domain: generic
  site_hash: true
  server_prefix: ''
  optimize: false
  fallback_multiple: true
dependencies:
  module:
    - search_api_solr
```

That seems different from what I see in your commit:

```yaml
* Server name: Solr Server
* Machine name: default_solr_server
* Enabled: yes
* Description (optional): Default Solr server created by the Solr Search Defaults module - config copied from https://git.drupalcode.org/project/search_api_solr/-/commit/1568d2b#4f547dbec1b001e0aa88f925637aa20132616c30
* Backend: Solr
* Solr connector: Standard
* Configure _Standard_ Solr connector:
* - HTTP protocol: http
* - Solr host: localhost
* - Solr port: 8983
* - Solr path: /
* - Solr core: drupal
* - Query timeout: 5
* - Index timeout: 10
* - Optimize timeout: 15
* - Finalize timeout: 30
* - Commit within: 10
* - Connector workarounds:
* -- Version override: determine automatically
* -- HTTP method: AUTO
* -- Skip schema verification: false
* - Advanced server configuration:
* -- Enable JMX: false
* -- Enable JTS
* -- solr.install.dir: '' (i.e. empty)
* Advanced:
* - Default result rows: 10
* - Index single documents fallback count: 10
* - Index empty fulltext fields: false
* - Retrieve result data from Solr: false
* - Retrieve highlighted snippets: false
* - Suppress warnings about...: false
* - Fallback to multiValued field types: false
* - All index prefix: '' (i.e. empty)
* - Targeted content domain: generic
* - Targeted environment: default
* - Optimize: false
* Multi-site compatibility:
* - Retrieve results for this site only: false
```

This is far outside my area of expertise, but if I could just link to a file like [this deleted one](https://git.drupalcode.org/project/search_api_solr/-/blob/e5c3b3cda58a7c838d63ae3962eff3345e47e184/modules/search_api_solr_defaults/config/optional/search_api.server.default_solr_server.yml), it'd be easier for maintenance.

**Comment by alexharriesredactive** [comment]
Hi @CollierCZ, as far as I can see the only difference is that my instructions list the field labels that a user will see in the Drupal UI, in the order they will see them.

The Yaml file you linked to contains machine labels and values, and asking a user to try and match these up to the fields in the Drupal UI would give a poor experience and cause confusion.

Best wishes,

Alex

**Review by CollierCZ — APPROVED** [review]
Thanks for your patience and help, @alexharriesredactive!

**Pull request merged**
