### PR TITLE
Clarify we are talking about the MRI

### PR DESCRIPTION
**Pull request by OriPekelman**

### CODE REVIEW

**Comment by sruggier** [comment]
I think we can clarify this point in a simpler way if we add a header so the outline looks like this:
### Supported versions
#### Ruby MRI
* 2.3

**Comment by Crell** [comment]
What's an MRI?

**Comment by JGrubb** [comment]
@Crell "Matz' Ruby Interpreter" - the original implementation of Ruby by the creator, as opposed to JRuby or Rubinius or YARV or any of the alternative Ruby implementations out there.

**Comment by OriPekelman** [comment]
Done in https://github.com/platformsh/platformsh-docs/commit/35ee0a46d8d0af9db6f5a62e301499b15dbb7a68

**Pull request closed without merging**
