### PR TITLE
Don't hardcode the info for connecting the DB

### PR DESCRIPTION
**Pull request by mrkschan**

### CODE REVIEW

**Comment by Crell** [comment]
I think we should at least link the new text to the appropriate page for the structure of the environment array, so people know how to get the domain out of it.

**Comment by mrkschan** [comment]
What if we use the one like Redis everywhere? https://github.com/platformsh/platformsh-docs/blob/master/src/configuration/services/redis.md#using-redis-cli-to-access-your-redis-service

**Comment by Crell** [comment]
Hm, that could work.  I'm all for better standardization across the services pages.

**Comment by mrkschan** [comment]
Updated

**Comment by Crell** [comment]
Thanks, KS!

**Pull request merged**
