### PR TITLE
Quick Start

### PR DESCRIPTION
**Pull request by OriPekelman**

### CODE REVIEW

**Comment by Crell** [comment]
This needs a lot more explanation of what it's actually doing.  It's not even slightly obvious.  And we may want to remove some other parts of the page if we're going to recommend this approach.  (Once I figured out what it was doing I like it better, but it's not even a little self-evident.)

I'll revise this.

**Comment by Crell** [comment]
Fleshed this out further.  I'm still not sure I like the "quick start" section, but it does seem useful to offer a one-liner.  Open to alternate suggestions there.

**Comment by Crell** [comment]
Actually no, with further testing the code here doesn't actually work.  PHP's local webserver isn't picking up the PLATFORM_RELATIONSHIPS env var.  Investigating further.

**Comment by Crell** [comment]
Figured it out.  PHP's webserver doesn't read env vars by default.  This is annoying.  I have documented that, as well as the other problem I spent too long chasing.  This is now tested and IMO mergable.

**Comment by pjcdawkins** [comment]
Technically env vars are available by default, but via `getenv()`, not via the $_ENV superglobal.

**Comment by Crell** [comment]
Damnit, PHP...

We are currently using $_ENV in all of our sample code; not for any particularly special reason, I guess.  We could change that but it wouldn't help current users if they read a command on this page that would only work the other way.  I'm open to suggestions on how we want to resolve that.

**Comment by pjcdawkins** [comment]
Release `platform server:start --tunnel`? That starts PHP web server(s) with the right variables_order. But it's not for everyone; it's not going to support fancy things like custom `start` commands etc.

**Comment by Crell** [comment]
That sounds complicated...  

Proposal: Merge the docs as-is, and then also switch our sample code over to use `getenv()` so it's less of an issue in the future.  Can I get an amen?  (By which I mean a merge.)

**Pull request merged**
