### PR TITLE
Googlesearch

### PR DESCRIPTION
**Pull request by robertDouglass**
This basically works. The image on the google "Search" button doesn't load correctly for me, but the search functionality works, and it's far better than the crap that is the default for Sphynx.

### CODE REVIEW

**Comment by GuGuss** [comment]
- [ ] This definitely needs theming
![search-icon](https://cloud.githubusercontent.com/assets/1927538/5643681/a4cf8362-965b-11e4-8513-6a92a77fe229.

**Comment by GuGuss** [comment]
@robertDouglass: This doesn't seem to work anymore.

**Comment by GuGuss** [comment]
Migrating to GitBook.

**Comment by robertDouglass** [comment]
We've done something new and horrible to our search. Maybe it's just a configuration, but it doesn't process them as HTML documents.
search platform sh documentation

**Pull request closed without merging**
