### PR TITLE
Change 3rd Party to Tandem.

### PR DESCRIPTION
**Pull request by serundeputy**

### CODE REVIEW

**Comment by Crell** [comment]
How about "by Tandem, a 3rd party agency, ..." ? :smile:

**Comment by JGrubb** [comment]
I personally think this is totally fine.

**Comment by serundeputy** [comment]
@Crell @JGrubb what say you all?  Leave or change it? Should I stay or should I go now? :) 🎵

**Comment by Crell** [comment]
I'd include the 3rd party mention, as otherwise the sentence is a bit clunky.  "It's maintained by Tandem, but it's really OK!" vs "It's maintained by Tandem who is a 3rd party, but it's really OK!"  (It's not that it's Tandem that requires the "no really, it's OK" but the fact that it's not-Platform but is still OK.)

**Comment by serundeputy** [comment]
@Crell thanks; updated the PR accordingly.

**Comment by Crell** [comment]
Merci bien.

**Pull request merged**
