### PR TITLE
:memo: Note routes resolve with trailing slashes

### PR DESCRIPTION
**Pull request by CollierCZ**
## Why

A change means that all routes will default to having trailing slashes. See additional context.

## What's changed

Added a section on trailing slashes with examples.

### CODE REVIEW

**Comment by trolologuy** [comment]
[Additional context](https://github.com/orgs/platformsh/projects/3/views/1) is missing the source information.

**Comment by CollierCZ** [comment]
Added

**Review by trolologuy — DISMISSED** [review]
- [x] Final built pages are working as expected.
- [x] The information is correct.
- [x] The information is comprehensive.
- [x] The information is concise.
- [x] The information is clear.
- [x] All links work, including to section headers.
- [x] The changes follow the content and markup style guides.

**Review by trolologuy — APPROVED** [review]
- [x] Final built pages are working as expected.
- [x] The information is correct.
- [x] The information is comprehensive.
- [x] The information is concise.
- [x] The information is clear.

**Pull request merged**
