### PR TITLE
Syntax highlight .environment

### PR DESCRIPTION
**Pull request by hanoii**
A little syntax highlighting doesn't harm anybody.

### CODE REVIEW

**Comment by hanoii** [comment]
I was hoping to double check ````bash` as I wasn't sure if it was OK but the build didn't kick in.

**Comment by demosdemon** [comment]
I poked the github integration for you. It should build soon.

**Comment by hanoii** [comment]
Shouldn't the check say why it failed :)?

**Comment by demosdemon** [comment]
Heh, that'd be helpful, wouldn't it? It does if you have access to the Platform.sh project.

    [0;31mError: ENOENT: no such file or directory, stat '/app/_book/gitbook/gitbook-plugin-fontsettings/fontsettings.js'[0m

Looks like something unrelated to your change. I'll dig in later.

**Comment by demosdemon** [comment]
All I did was redeploy and it worked just fine. I hate Gitbook sometimes.

**Pull request merged**
