### PR TITLE
Updates `whitelist` to `safe-list` across docs

### PR DESCRIPTION
**Pull request by JGrubb**

### CODE REVIEW

**Comment by robertDouglass** [comment]
Please reopen this and replace whitelist and blacklist anywhere they occur in our documentation.

**Comment by Crell** [comment]
With a word that has contextually relevant meaning, which "safelist" does not.

**Comment by robertDouglass** [comment]
Personally I feel that "blocked" or "blocked list", and "allowed", or "allowed list" are the appropriate replacements.

**Comment by Crell** [comment]
Closing in favor of #1459

**Pull request closed without merging**
