### PR TITLE
Add troubleshot section to ruby for BUNDLE_DEPLOYMENT=1

### PR DESCRIPTION
**Pull request by spk**
## Why

Report by @Theosakamg on his project

## What's changed

Add troubleshot section to ruby for BUNDLE_DEPLOYMENT=1, this need a explanation for ruby users that are not expert on those issues

### CODE REVIEW

**Comment by CollierCZ** [comment]
@spk , thanks for the suggestion! This means that `BUNDLE_DEPLOYMENT` is already set to `1` by default, right? Are any of the other variables [listed as "will be default"](https://pr-2101-crnshwi-652soceglkw4u.eu-3.platformsh.site/languages/ruby.html#unicorn-based-rails-configuration) already switched over or just this one?

**Comment by spk** [comment]
@CollierCZ  Yes the project is on EU-3, not sure about the other regions, all of them should be the defaults soon

Should I change the `will be` by `the current default`?

**Comment by CollierCZ** [comment]
I can change it, no worries. Just wasn't sure if it was for the one or for all of them.

**Comment by spk** [comment]
> I can change it, no worries. Just wasn't sure if it was for the one or for all of them.

Ok no problemo, I think only this one will cause issues with builds failing the others should be fine with existing projects

**Review by CollierCZ — APPROVED** [review]

**Pull request merged**
