### PR TITLE
✨ Automate template info

### LINKED ISSUE #2388: 📝 Add Django4 template to list of templates
### Where on docs.platform.sh should be changed?

https://github.com/platformsh/platformsh-docs/blob/main/docs/data/templates.yaml

https://docs.platform.sh/development/templates.html#python and
https://docs.platform.sh/languages/python.html#project-templates

### What exactly should be updated?

[Django4 template](https://github.com/platformsh-templates/django4) needs to be added 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by CollierCZ**
## Why

Closes #2388 

## What's changed

Added a new script to pull template info from the template builder repository
Added to build process
Updated to `js-yaml` 4 (including the registry parser)

### CODE REVIEW

**Review by trolologuy — COMMENTED** [review]
How precisely should I review this one? Anything specific to look out for besides checking the templates listing for the languages?

**Comment by CollierCZ** [comment]
If you'd like, you can try deleting the file locally and rebuilding and making sure it works.

A check of the code would be cool, seeing if it makes some sense and it's at least clear which parts do what.

But the main idea is the output, so yeah, I'd focus mostly there.

**Comment by CollierCZ** [comment]
It should be enough to do up to step 3 and see the file. 
* Did you not get any error messages after running `npm run dev`? 
  `Error loading the YAML file with info on the flask template` is expected and doesn't count.
* Did you see the message `### Getting info on Platform.sh templates`?
* Did you run the commands from the `docs` directory? I ask because `rm -rf docs/data/templates.yaml` is unexpected in terms of the location and the flags (it's a file, so not sure why it needs to be recursive)

**Review by trolologuy — COMMENTED** [review]
<details>
<summary>First run</summary>
```
➜ npm install && npm run dev
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

added 1591 packages, and audited 1592 packages in 51s

141 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice
npm notice New minor version of npm available! 8.1.0 -> 8.12.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.12.1
npm notice Run npm install -g npm@8.12.1 to update!
npm notice

> platformsh-docs@1.0.0 dev
> npm run fetch-files && npm run registry-files


> platformsh-docs@1.0.0 fetch-files
> node static/scripts/fetch-examples.mjs

Fetching https://raw.githubusercontent.com/platformsh-templates/typo3/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/drupal7/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/drupal8/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/drupal9/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/akeneo/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/magento2ce/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/spring-boot-maven-mysql/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/drupal8-multisite/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/pyramid/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/php/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/golang/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/python3/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/nodejs/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/typo3/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-composer/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-vanilla/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/quarkus/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/spring-mvc-maven-mongodb/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/micronaut/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/strapi4/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/laravel/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/drupal9/master/web/sites/default/settings.platformsh.php
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-drupal/master/gatsby/gatsby-config.js
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-strapi/master/gatsby/gatsby-config.js
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-wordpress/master/gatsby/gatsby-config.js
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-composer/master/.lando.upstream.yml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-vanilla/master/.lando.upstream.yml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-drupal/master/gatsby/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-strapi/master/gatsby/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-wordpress/master/gatsby/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/php/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-drupal/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-strapi/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-wordpress/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/quarkus/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/spring-mvc-maven-mongodb/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/micronaut/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/drupal9/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-vanilla/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-composer/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/typo3/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/strapi4/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/laravel/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/drupal9/master/.platform/services.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/typo3/master/.platform/services.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-composer/master/.platform/services.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-vanilla/master/.platform/services.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-drupal/master/.platform/services.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-strapi/master/.platform/services.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-wordpress/master/.platform/services.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/typo3/master/public/typo3conf/PlatformshConfiguration.php
Fetching https://raw.githubusercontent.com/platformsh-templates/typo3/master/config/sites/main/config.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-vanilla/master/wordpress/wp-config.php
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-composer/master/wp-config.php
Fetching https://examples.docs.platform.sh/golang/memcached
Fetching https://examples.docs.platform.sh/golang/mongodb
Fetching https://examples.docs.platform.sh/golang/mysql
Fetching https://examples.docs.platform.sh/golang/postgresql
Fetching https://examples.docs.platform.sh/golang/rabbitmq
Fetching https://examples.docs.platform.sh/golang/solr
Fetching https://examples.docs.platform.sh/java/elasticsearch
Fetching https://examples.docs.platform.sh/java/kafka
Fetching https://examples.docs.platform.sh/java/memcached
Fetching https://examples.docs.platform.sh/java/mongodb
Fetching https://examples.docs.platform.sh/java/mysql
Fetching https://examples.docs.platform.sh/java/postgresql
Fetching https://examples.docs.platform.sh/java/rabbitmq
Fetching https://examples.docs.platform.sh/java/redis
Fetching https://examples.docs.platform.sh/java/solr
Fetching https://examples.docs.platform.sh/nodejs/elasticsearch
Fetching https://examples.docs.platform.sh/nodejs/memcached
Fetching https://examples.docs.platform.sh/nodejs/mongodb
Fetching https://examples.docs.platform.sh/nodejs/mysql
Fetching https://examples.docs.platform.sh/nodejs/postgresql
Fetching https://examples.docs.platform.sh/nodejs/redis
Fetching https://examples.docs.platform.sh/nodejs/solr
Fetching https://examples.docs.platform.sh/php/elasticsearch
Fetching https://examples.docs.platform.sh/php/influxdb
Fetching https://examples.docs.platform.sh/php/memcached
Fetching https://examples.docs.platform.sh/php/mongodb
Fetching https://examples.docs.platform.sh/php/mysql
Fetching https://examples.docs.platform.sh/php/postgresql
Fetching https://examples.docs.platform.sh/php/rabbitmq
Fetching https://examples.docs.platform.sh/php/redis
Fetching https://examples.docs.platform.sh/php/solr
Fetching https://examples.docs.platform.sh/python/elasticsearch
Fetching https://examples.docs.platform.sh/python/kafka
Fetching https://examples.docs.platform.sh/python/memcached
Fetching https://examples.docs.platform.sh/python/mongodb
Fetching https://examples.docs.platform.sh/python/mysql
Fetching https://examples.docs.platform.sh/python/postgresql
Fetching https://examples.docs.platform.sh/python/rabbitmq
Fetching https://examples.docs.platform.sh/python/rabbitmq
Fetching https://examples.docs.platform.sh/python/redis
Fetching https://examples.docs.platform.sh/python/solr
Fetching https://examples.docs.platform.sh/relationships/elasticsearch
Fetching https://examples.docs.platform.sh/relationships/headlesschrome
Fetching https://examples.docs.platform.sh/relationships/influxdb
Fetching https://examples.docs.platform.sh/relationships/kafka
Fetching https://examples.docs.platform.sh/relationships/memcached
Fetching https://examples.docs.platform.sh/relationships/mongodb
Fetching https://examples.docs.platform.sh/relationships/mysql
Fetching https://examples.docs.platform.sh/relationships/oraclemysql
Fetching https://examples.docs.platform.sh/relationships/opensearch
Fetching https://examples.docs.platform.sh/relationships/postgresql
Fetching https://examples.docs.platform.sh/relationships/postgresql
Fetching https://examples.docs.platform.sh/relationships/rabbitmq
Fetching https://examples.docs.platform.sh/relationships/redis
Fetching https://examples.docs.platform.sh/relationships/solr
Fetching https://examples.docs.platform.sh/relationships/vault-kms

> platformsh-docs@1.0.0 registry-files
> node static/scripts/updateExampleConfigFiles.js


### updateExampleConfigFiles.js: Updating example Platform.sh configuration yamls.
```
</details>

<details>
<summary>Second run</summary>
```
platformsh-docs/docs on  main [!?] is 📦 v1.0.0 via ⬢ v16.13.0 took 1m 0s
➜ npm install && npm run dev

up to date, audited 1592 packages in 3s

141 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> platformsh-docs@1.0.0 dev
> npm run fetch-files && npm run registry-files


> platformsh-docs@1.0.0 fetch-files
> node static/scripts/fetch-examples.mjs

Fetching https://raw.githubusercontent.com/platformsh-templates/typo3/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/drupal7/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/drupal8/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/drupal9/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/akeneo/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/magento2ce/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/spring-boot-maven-mysql/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/drupal8-multisite/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/pyramid/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/php/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/golang/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/python3/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/nodejs/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/typo3/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-composer/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-vanilla/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/quarkus/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/spring-mvc-maven-mongodb/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/micronaut/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/strapi4/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/laravel/master/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/drupal9/master/web/sites/default/settings.platformsh.php
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-drupal/master/gatsby/gatsby-config.js
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-strapi/master/gatsby/gatsby-config.js
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-wordpress/master/gatsby/gatsby-config.js
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-composer/master/.lando.upstream.yml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-vanilla/master/.lando.upstream.yml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-drupal/master/gatsby/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-strapi/master/gatsby/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-wordpress/master/gatsby/.platform.app.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/php/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-drupal/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-strapi/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-wordpress/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/quarkus/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/spring-mvc-maven-mongodb/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/micronaut/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/drupal9/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-vanilla/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-composer/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/typo3/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/strapi4/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/laravel/master/.platform/routes.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/drupal9/master/.platform/services.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/typo3/master/.platform/services.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-composer/master/.platform/services.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-vanilla/master/.platform/services.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-drupal/master/.platform/services.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-strapi/master/.platform/services.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/gatsby-wordpress/master/.platform/services.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/typo3/master/public/typo3conf/PlatformshConfiguration.php
Fetching https://raw.githubusercontent.com/platformsh-templates/typo3/master/config/sites/main/config.yaml
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-vanilla/master/wordpress/wp-config.php
Fetching https://raw.githubusercontent.com/platformsh-templates/wordpress-composer/master/wp-config.php
Fetching https://examples.docs.platform.sh/golang/memcached
Fetching https://examples.docs.platform.sh/golang/mongodb
Fetching https://examples.docs.platform.sh/golang/mysql
Fetching https://examples.docs.platform.sh/golang/postgresql
Fetching https://examples.docs.platform.sh/golang/rabbitmq
Fetching https://examples.docs.platform.sh/golang/solr
Fetching https://examples.docs.platform.sh/java/elasticsearch
Fetching https://examples.docs.platform.sh/java/kafka
Fetching https://examples.docs.platform.sh/java/memcached
Fetching https://examples.docs.platform.sh/java/mongodb
Fetching https://examples.docs.platform.sh/java/mysql
Fetching https://examples.docs.platform.sh/java/postgresql
Fetching https://examples.docs.platform.sh/java/rabbitmq
Fetching https://examples.docs.platform.sh/java/redis
Fetching https://examples.docs.platform.sh/java/solr
Fetching https://examples.docs.platform.sh/nodejs/elasticsearch
Fetching https://examples.docs.platform.sh/nodejs/memcached
Fetching https://examples.docs.platform.sh/nodejs/mongodb
Fetching https://examples.docs.platform.sh/nodejs/mysql
Fetching https://examples.docs.platform.sh/nodejs/postgresql
Fetching https://examples.docs.platform.sh/nodejs/redis
Fetching https://examples.docs.platform.sh/nodejs/solr
Fetching https://examples.docs.platform.sh/php/elasticsearch
Fetching https://examples.docs.platform.sh/php/influxdb
Fetching https://examples.docs.platform.sh/php/memcached
Fetching https://examples.docs.platform.sh/php/mongodb
Fetching https://examples.docs.platform.sh/php/mysql
Fetching https://examples.docs.platform.sh/php/postgresql
Fetching https://examples.docs.platform.sh/php/rabbitmq
Fetching https://examples.docs.platform.sh/php/redis
Fetching https://examples.docs.platform.sh/php/solr
Fetching https://examples.docs.platform.sh/python/elasticsearch
Fetching https://examples.docs.platform.sh/python/kafka
Fetching https://examples.docs.platform.sh/python/memcached
Fetching https://examples.docs.platform.sh/python/mongodb
Fetching https://examples.docs.platform.sh/python/mysql
Fetching https://examples.docs.platform.sh/python/postgresql
Fetching https://examples.docs.platform.sh/python/rabbitmq
Fetching https://examples.docs.platform.sh/python/rabbitmq
Fetching https://examples.docs.platform.sh/python/redis
Fetching https://examples.docs.platform.sh/python/solr
Fetching https://examples.docs.platform.sh/relationships/elasticsearch
Fetching https://examples.docs.platform.sh/relationships/headlesschrome
Fetching https://examples.docs.platform.sh/relationships/influxdb
Fetching https://examples.docs.platform.sh/relationships/kafka
Fetching https://examples.docs.platform.sh/relationships/memcached
Fetching https://examples.docs.platform.sh/relationships/mongodb
Fetching https://examples.docs.platform.sh/relationships/mysql
Fetching https://examples.docs.platform.sh/relationships/oraclemysql
Fetching https://examples.docs.platform.sh/relationships/opensearch
Fetching https://examples.docs.platform.sh/relationships/postgresql
Fetching https://examples.docs.platform.sh/relationships/postgresql
Fetching https://examples.docs.platform.sh/relationships/rabbitmq
Fetching https://examples.docs.platform.sh/relationships/redis
Fetching https://examples.docs.platform.sh/relationships/solr
Fetching https://examples.docs.platform.sh/relationships/vault-kms

> platformsh-docs@1.0.0 registry-files
> node static/scripts/updateExampleConfigFiles.js


### updateExampleConfigFiles.js: Updating example Platform.sh configuration yamls.
```
</details>

**Review by trolologuy — CHANGES_REQUESTED** [review]
- [x] Final built pages are working as expected.
- [x] All links work, including to section headers.

There is a small difference in how logos are scaled making some of them hard to see. [Original](https://docs.platform.sh/languages/ruby.html#project-templates) vs [now](https://pr-2396-siijbyi-652soceglkw4u.eu-3.platformsh.site/languages/ruby.html#project-templates).
The [Django4 template now appears](https://pr-2396-siijbyi-652soceglkw4u.eu-3.platformsh.site/languages/python.html#project-templates), although this logo isn't scaled.

Other than that it seems to work as expected.

**Pull request merged**
