### PR TITLE
Add note to downsizing disk of a service

### PR DESCRIPTION
**Pull request by mrkschan**

### CODE REVIEW

**Comment by Crell** [comment]
As in #314, what happens if you try? Error? It silently ignores you? That should be included in the docs in both places.

**Comment by Crell** [comment]
Tweaked language per discussion with @damz. Someone commit if this is now accurate.

**Comment by mrkschan** [comment]
@robertDouglass please review the changes.

**Comment by Crell** [comment]
@mrkschan Please merge if you're comfortable here.

**Comment by sruggier** [comment]
I've merged the original commit.

**Comment by Crell** [comment]
Er?  The original commit was incomplete, as noted, as it actively left the user wondering what would happen.  That's why we added more text.  Please don't merge something that's incomplete.

**Pull request closed without merging**
