### PR TITLE
Algolia search option

### PR DESCRIPTION
**Pull request by OriPekelman**
This seems to work better than addsearch. I would go for Aloglia. Needs to be implemented properly do not merge.

### CODE REVIEW

**Comment by Crell** [comment]
image

Neither Troubleshooting nor PHP Support are under "The Big Picture", and Redis is not under MySQL.

If those sections were accurate that would be a pretty nice search engine, but it's rather misleading as is.

**Comment by maxiloc** [comment]
I updated the config, should be fixed now.

**Comment by Crell** [comment]
I spent some time looking into running the indexer ourselves.  Unfortunately it depends on a couple of additional C packages that are not installed on Psh containers, and adding the headers for them is more work than I want to put into the docs for right now.  Which is a bit unfortunate as it seems that would allow us to have at least basic analytics for docs search, which would be nice.

In any case, turning this over to Aaron for now to style.  Aaron, let's just try to swap the current search box out for the Algolia one.  Nothing fancy needed.

**Comment by maxiloc** [comment]
We can provide analytics for the index on the DocSearch account. @OriPekelman, you can send me the list of emails that need access, and I'll invite them.

**Comment by dudenhofer** [comment]
Updated the styles and removed the old search plugin we were using. Seems to be working just fine to me.

**Comment by OriPekelman** [comment]
This should also be test _after_ merging... remember the google custom search bug... As far as I concerned can be merged

**Comment by Crell** [comment]
Everything checks out for me in spot checks on desktop.  However, I just checked it on mobile for the first time (I should have checked it earlier) and the pop-over is not resizing for mobile, making it very difficult to use.  Is that something that could be fixed on our end or is that on Algolia to fix on their end?  

Paging @maxiloc for input on that front...

**Comment by Crell** [comment]
Much nicer.  Thanks, Aaron!

**Pull request merged**
