### PR TITLE
📝 Document how to cancel activities

### LINKED ISSUE #2677: 📝 Note how to cancel activities
### What needs to be documented?

In the upcoming version of the API Server, in-progress build and source operation activities will be able to be cancelled. Currently, only pending build activities and cron jobs can be canceled.

We don't have anything on how to cancel activities, so we should probably add something describing how to do it in the CLI and Console. It's possible support in the Console won't be complete, but `platform activity:cancel` should still work.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by CollierCZ**
## Why

Closes #2677

## What's changed

Added a page on how to cancel activities with instructions for CLI and Console

### CODE REVIEW

**Review by AnouckColson — DISMISSED** [review]
🚀  Seems good to go!

**Review by AnouckColson — CHANGES_REQUESTED** [review]
Just noticed the display was off due to a typo, otherwise it's all good!

**Comment by CollierCZ** [comment]
Good point, thanks!

**Review by AnouckColson — APPROVED** [review]
🚀 👍

**Pull request merged**
