### PR TITLE
[Redis] Remove Confusion with Relationship name

### PR DESCRIPTION
**Pull request by Plopix**
The documentation is unclear to me, it is confusing when it comes to the relationship name.

The `Assuming your Redis relationship is named 'rediscache'` is weird as in the previous configuration `rediscache` is just the name of the service.

Letting `redis` as the name is also a bit confusing to me. Then I have added the configuration again to make it clear.

Let me know

Best,

### CODE REVIEW

**Comment by pjcdawkins** [comment]
Thanks, this is definitely an improvement. I've added a commit to update the previous example to `myredis` for consistency.

**Comment by Crell** [comment]
I've been trying to actively avoid "my*" as a name for services, as it's not particularly descriptive or extensible.  "my*" examples generally are not very good.

The rest of the changes here I like, especially adding how to use Redis for native sessions.  Let's try for a better relationship name, though.  I'm open to suggestions.

**Comment by Plopix** [comment]
fair enough @Crell! I renamed with `fooredis`.

Let me know! ping @pjcdawkins

**Comment by Crell** [comment]
eh, `foo` isn't really much better.  It's just `my` with an extra character. :smile: The intent should be to have default names that people can really use, because most will be copy-pasting it so we want meaningful examples.

**Comment by pjcdawkins** [comment]
I suggest `redis`!

**Comment by Plopix** [comment]
@Crell how about now? `applicationcache` and `sessionstorage`
@pjcdawkins To me using `redis` would introduce another confusion with the `endpoint`

> I think if these names are still not good, @Crell you should decide and tell us ;) OR we should merge and decide/update later (creating an issue)

**Comment by Crell** [comment]
applicationcache and sessionstorage actually sound great.  Specific, descriptive, all the good things.  :+1: 

Thanks, @Plopix!

**Pull request merged**
