### PR TITLE
Apply editorconfig to all .md files

### PR DESCRIPTION
**Pull request by mrkschan**
Using https://github.com/treyhunner/editorconfig-tools to apply the editorconfig on all markdown files.

### CODE REVIEW

**Comment by mrkschan** [comment]
FYI, this include a lot of white space and new line changes.... For non white space / new line changes, see https://github.com/platformsh/platformsh-docs/pull/337/files?w=1 (which is nothing to be shown).

**Comment by Crell** [comment]
Yikes, that's a lot of whitespace! :smile: 

It looks like this is also running over the code portions of the repo, not just the markdown files.  Is it possible to exclude those and just touch the markdown?  (I don't want to do anything to code in node_modules if I can help it. That's a separate matter.)

**Comment by mrkschan** [comment]
Interesting... I don't know there's embedded node_modules :)

**Comment by Crell** [comment]
Honestly neither did I. :smile: Although... bah, the PR I just merged broke this one, too.  (Fragile PRs are fragile...)

**Comment by JGrubb** [comment]
Ok, I reviewed all 94 files, and it is only .md files and only whitespace.  Are we happy with this one?

**Comment by mrkschan** [comment]
Rebased!

**Comment by Crell** [comment]
Argh! Just broken by #333.

Maybe we shouldn't do a repo-wide cleanup on this, at lest not right now....

**Comment by mrkschan** [comment]
No... if we don't do this early ... we will just have PRs that change some whitespaces randomly because of editorconfig ...

**Comment by mrkschan** [comment]
Merging this since this's just some whitespace changes for editorconfig.

**Pull request merged**
