### PR TITLE
Adding some diagrams to config docs

### PR DESCRIPTION
**Pull request by JGrubb**

### CODE REVIEW

**Comment by OriPekelman** [comment]
This is a huge improvement. So let's merge this and let Igor redo those prettily later ?

**Comment by JGrubb** [comment]
Thanks @OriPekelman .  I'd like to get a thumbs up from @Crell before moving the prototype into production tho.

**Comment by pjcdawkins** [comment]
"Typical Platform Professional Architecture" should just be "Typical Platform.sh Architecture"

**Comment by OriPekelman** [comment]
I am going to say this again: I strongly believe that on documentation obvious / trivial corrections should, most of the time, just be directly committed to the branch. It is a sane default. You know this is git. We can revert.

**Comment by pjcdawkins** [comment]
Agreed. If that's in response to me... I would certainly commit that correction, if I could easily edit the JPEG.

**Comment by JGrubb** [comment]
I mean, the whole point of these diagrams was as prototype, and to have them replaced by someone with some design skill.  Let’s just incorporate that into the next version.

**Comment by Crell** [comment]
OK, let's do this!

**Pull request merged**
