### PR TITLE
--room parameter doesn't exist

### PR DESCRIPTION
**Pull request by isholgueras**
The correct parameter is --hipchat-room-id

### CODE REVIEW

**Comment by Crell** [comment]
Hm, are you sure?  It looks like it's "room" in our code, both on the server and in the CLI client.

**Comment by pjcdawkins** [comment]
Ah. Looks like a regression in the CLI

**Comment by pjcdawkins** [comment]
... fixed in v3.14.0 of the CLI - sorry about that (and thanks for the PR)

**Comment by isholgueras** [comment]
That's why I made the PR:
issue

No problem @pjcdawkins.

Thanks for the fix.

**Pull request closed without merging**
